name: figchronicles
favicon: null
layout_spectrum: 1
typography_spectrum: 0.34589
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e6e3d2'
    - '#23121c'
    - '#2c3c0b'
    - '#84716a'
    - '#9ea41e'
  brandStrength: 0.3125
  lightness: 0.75
  saturation: 0.4375
  rhythmicContrast: 0.27902607060968876
purpose: []
