name: figchronicles
favicon: null
layout_spectrum: 0.33467630785889924
typography_spectrum: 0.16852295631542802
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.4728159988299012
  lightness: 0.7897141601424664
  saturation: 0.4818223286420107
  rhythmicContrast: 0.27902607060968876
purpose: []
